version: '3.8'

services:
  db:
    container_name: task_database
    image: postgres:14.1-alpine
    # restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
    ports:
      - '54322:5432'
    volumes: 
        - database-data:/var/lib/postgresql/data/

  app:
      build: .
      container_name: task_app
      command: >
        sh -c "./wait-for.sh db:54322 --
          python manage.py runserver 0.0.0.0:8080"
      volumes:
        - app:/src
      ports:
        - "8080:8080"
      depends_on:
        - db

volumes:
  database-data:
    driver: local
  app:
    driver: local
